# Generated by Django 2.1.7 on 2019-04-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
