# Generated by Django 2.1.7 on 2019-04-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_delete_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='accout',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
