# Generated by Django 2.1.7 on 2019-04-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_auto_20190414_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplane',
            old_name='embargo',
            new_name='delay',
        ),
    ]
