# Generated by Django 2.1.7 on 2019-04-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0005_auto_20190414_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='accout',
            new_name='account',
        ),
    ]
